imdb:
  url: https://imdb-api.com/en/API
  key: ${IMDB_API_KEY}

spring:
  profiles:
    active: dev

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: imersao-java
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  web:
    resources:
      static-locations: classpath:/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:sticker/

topic:
  sticker: generator-sticker

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.imersao.spring: debug
